name: Railway Dev
values:
  - key: baseUrl
    value: 'https://your-project.up.railway.app'
    enabled: true
    type: default
  - key: admin_email
    value: 'admin@example.com'
    enabled: true
    type: default
  - key: admin_password
    value: 'your_admin_password'
    enabled: true
    type: default
  - key: adminToken
    value: ''
    enabled: true
    type: default
  - key: user_email
    value: 'user@test.com'
    enabled: true
    type: default
  - key: user_password
    value: 'your_user_password'
    enabled: true
    type: default
  - key: user_name
    value: 'Test User'
    enabled: true
    type: default
  - key: userToken
    value: ''
    enabled: true
    type: default
