// AUTO-GENERATED CONFIGURATION FILE
// Do not edit this file directly. Update the root .env file and run `npm run kiosk:config` instead.
#ifndef KIOSK_CONFIG_H
#define KIOSK_CONFIG_H

const char *ssid = "OplorHotspot";
const char *password = "1212312121";
const char *serverUrl = "http://10.89.160.230:3000";

#endif // KIOSK_CONFIG_H
