import os
import re

# Resolve paths
ROOT_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ENV_FILE = os.path.join(ROOT_DIR, ".env")
KIOSK_CONFIG = os.path.join(ROOT_DIR, "kiosk", "kiosk_main", "kiosk_config.h")


def parse_env(file_path):
    env_vars = {}
    if not os.path.exists(file_path):
        print(f"Warning: {file_path} not found.")
        return env_vars

    with open(file_path, "r") as f:
        for line in f:
            line = line.strip()
            # Ignore comments and empty lines
            if not line or line.startswith("#"):
                continue

            # Simple key=value parsing
            if "=" in line:
                key, value = line.split("=", 1)
                # Remove quotes from value if present
                value = value.strip("\"'")
                env_vars[key.strip()] = value

    return env_vars


def generate_header(env_vars, output_path):
    # Fallbacks in case .env doesn't have these
    ssid = env_vars.get("WIFI_SSID", "OplorHotspot")
    password = env_vars.get("WIFI_PASSWORD", "1212312121")
    url = env_vars.get("NEXT_PUBLIC_API_URL", "http://10.66.10.246:3000")

    mqtt_host = env_vars.get("MOSQUITTO_TCP_HOST", "")
    mqtt_port = env_vars.get("MOSQUITTO_TCP_PORT", "1883")
    mqtt_user = env_vars.get("MOSQUITTO_USER", "")
    mqtt_password = env_vars.get("JWT_SECRET", "")

    header_content = f"""// AUTO-GENERATED CONFIGURATION FILE
// Do not edit this file directly. Update the root .env file and run `npm run kiosk:config` instead.
#ifndef KIOSK_CONFIG_H
#define KIOSK_CONFIG_H

// --- WiFi ---
const char *ssid = "{ssid}";
const char *password = "{password}";

// --- Backend API ---
const char *serverUrl = "{url}";

// --- MQTT Broker ---
const char *mqttHost     = "{mqtt_host}";
const int   mqttPort     = {mqtt_port};
const char *mqttUser     = "{mqtt_user}";
const char *mqttPassword = "{mqtt_password}";

#endif // KIOSK_CONFIG_H
"""

    # Ensure directory exists
    os.makedirs(os.path.dirname(output_path), exist_ok=True)

    with open(output_path, "w") as f:
        f.write(header_content)

    print(f"✅ Generated {output_path} successfully from .env mapping.")
    print(f"   -> SSID:      {ssid}")
    print(f"   -> API URL:   {url}")
    print(f"   -> MQTT Host: {mqtt_host}:{mqtt_port}")
    print(f"   -> MQTT User: {mqtt_user}")


if __name__ == "__main__":
    env_vars = parse_env(ENV_FILE)
    generate_header(env_vars, KIOSK_CONFIG)
